nome = input("Digite seu nome: ")
cpf = input("Digite seu CPF: ")
endereco = input("Digite seu endereço: ")
idade = input("Digite sua idade: ")
altura = input("Digite sua altura: ")
telefone = input("Digite seu telefone: ")

print("##############")
print('Nome do Usuário:', nome)
print('CPF:', cpf)
print('Endereço:', endereco)
print("Idade:", idade)
print("Altura:", altura)
print("Contato:", telefone)
print("##############")
